apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: rollout-demo-2-mapping-1654204162807
  namespace: my-app-2
spec:
  service: rollout-demo-2.my-app-2:80
  timeout_ms: 3000
  connect_timeout_ms: 3000
  retry_policy:
    retry_on: 5xx
    num_retries: 1
    per_try_timeout: 0.150s
  hostname: "*"
  prefix: /test
