apiVersion: v1
kind: Service
metadata:
  labels:
    app: rollout-demo-2
  name: rollout-demo-2-canary
  namespace: my-app-2
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: rollout-demo-2
